[SUPDESQ-29] - added mapping for RDF
salsadigitalauorg/ckanext-qdes-schema pull request #222
Opened 2022-01-03 03:49 UTC by awset

https://salsadigital.atlassian.net/browse/SUPDESQ-29

2022-01-03 15:46 UTC, tino097 approved these changes

2022-01-12 18:15 UTC, tino097 approved these changes

2022-03-16 02:13 UTC, MarkCalvert approved these changes

2022-03-16 03:12 UTC, MarkCalvert requested changes
Hi @awset,

Everything looks good but when I did a quick smoke test I noticed the postionID was being exported instead of the contact name.
This needs to be updated to match `AC3 All contact information is converted from Position Id to contact name`
We did something similar for the XML export in `dataset_export` to get the `get_secure_vocabulary_record`.
Go through the schema and make sure all metadata fields that use          `"vocabulary_service_name": "point-of-contact"` are converted to use contact name before exporting.

2022-03-25 00:14 UTC, MarkCalvert approved these changes

2022-03-25 00:14 UTC, merged